version: '3.4'

services:
  db:
    build:
      context: db
    restart: always
    environment:
      POSTGRES_USER: ding
      POSTGRES_PASSWORD: example
      POSTGRES_DB: suedtirol

  ontop:
    image: ontop/ontop-endpoint:geof
    volumes:
      - ./ontop/vkg:/opt/ontop/input
      - ./ontop/jdbc:/opt/ontop/jdbc
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/suedtirol_merged.owl
      ONTOP_MAPPING_FILE: /opt/ontop/input/suedtirol.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/suedtirol.docker.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/suedtirol.portal.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
    ports:
      - 8080:8080

  web:
    image:
      nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - 80:80

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#    volumes:
#      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
