title="Sued Tirol Open Data Analysis"

[[tabGroups]]

name="Sensor Analysis"

[[tabGroups.tabs]]

name="sensors in Bolanzo and their observations"
query="""
PREFIX : <http://ex.org/suedtirol#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX terms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

SELECT ?pName ?v ?t ?prop  WHERE {
  ?m a  :Municipality .
  ?m rdfs:label 'Bolzano'@it.
  ?m geo:asWKT ?mWkt .
  ?s a sosa:Sensor .
  ?s sosa:isHostedBy ?p.
  ?p rdfs:label ?pName .
  ?p geo:defaultGeometry ?g .
  ?g geo:asWKT ?pWkt .
  FILTER (LANG(?pName)='it')
  FILTER (geof:sfWithin(?pWkt, ?mWkt))
  ?s sosa:madeObservation ?o .
  ?o sosa:observedProperty ?prop .
  ?o sosa:hasSimpleResult ?v . ?o sosa:resultTime ?t .
  FILTER (?t >= '2017-01-01T00:00:00'^^xsd:dateTime)
  FILTER (?t <= '2017-01-31T00:00:00'^^xsd:dateTime)
}
"""
